version: '2'

volumes:
  postgres_data_local: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    env_file:
      - ./envs/postgres.env
    image: django
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  postgres:
    env_file:
      - ./envs/postgres.env
    image: postgres:10.4
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
